[package]
name = "ferristream"
version = "0.1.0"
edition = "2021"

[dependencies]
librqbit = "8.1.1"
ratatui = "0.29.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
directories = "5.0"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1"
